version: '3.8'
services:
  php-apache-evironment:
    image: bisma/quiz
    container_name: php-apache
    depends_on:
      - db
    volumes:
      - /var/www/html/web-php-bookstoreQ
    ports:
      - 8000:80
    networks:
      - backend

    db:
      container_name: db
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: buku
      ports:
        - "3306:3306"
      volumes:
        - db/var/lib/mysql
        - ./db_buku.sql:/docker-entrypoint-initdb.d/db_buku.sql
      networks:
        - backend

volumes:
  db:

networks:
  backend:
    name: backend-network
    ipam:
      driver: default
      config:
        - subnet: 172.17.0.0/24